build: *.c *.h
	gcc init.h init.c globalData.h globalData.c serverCommand.h serverCommand.c prepareInstruction.h prepareInstruction.c fileRelated.h fileRelated.c server.c -Wall -o server -lpthread 
clean:
	rm server